version: '3'

x-base: &base
    env_file:
        - .env


networks:
  API:
    driver: bridge


services:

  redis:
    image: redis
    container_name: 'redis_cache'
    restart: unless-stopped
    networks:
      - API
    volumes:
      - ./redis/data:/data
    expose:
      - ${REDIS_PORT}

    healthcheck:
      test: [ "CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  pg:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - API
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    expose:
      - ${POSTGRES_PORT}


  api:
    build:
      context: auth_api
    env_file:
      - .env
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - API
    depends_on:
      redis:
        condition: service_healthy

#  nginx:
#    image: nginx:latest
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./nginx/configs:/etc/nginx/templates:ro
#    environment:
#      NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".template"
#      NGINX_SET_REAL_IP_FROM: 192.168.1.0/24
#      API_PORT: ${API_PORT}
#      FAST_API_PORT: ${FAST_API_PORT}
#    depends_on:
#      - api
#    networks:
#      - API
#    ports:
#      - ${NGINX_PORT}:80